version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mureca
      POSTGRES_DB: shop
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  nest-api:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    restart: always

volumes:
  postgres-data:
  pgadmin-data:
  redis-data: