version: '3.8'
services:
  nest-api:
    image: nest-api:latest 
    container_name: nest-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env  
    environment:
      POSTGRES_DB: "testenestjs"
      POSTGRTES_USER: "postgres"
      POSTGRES_PASSWORD: "mureca"

  
